# Generated by Django 5.2 on 2025-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_age_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g., 2020-2024', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_field',
            field=models.CharField(blank=True, help_text='e.g., Computer Science, Business, etc.', max_length=100),
        ),
    ]
