# Generated by Django 5.2 on 2025-05-01 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandarin_vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandarin_vocab.vocabularyword'),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'word')},
        ),
    ]
