# Generated by Django 5.2 on 2025-05-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandarin_vocab', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_chapters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='mandarin_vocab.hskbook')),
                ('vocabulary_list', models.ManyToManyField(blank=True, related_name='chapters', to='mandarin_vocab.vocabularyword')),
            ],
            options={
                'verbose_name': 'Book Chapter',
                'verbose_name_plural': 'Book Chapters',
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
    ]
