# Generated by Django 5.2 on 2025-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandarin_vocab', '0003_bookchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='chinese_text',
            field=models.TextField(blank=True, help_text='Lesson text in Chinese'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='cultural_notes',
            field=models.TextField(blank=True, help_text='Cultural context and notes'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='english_text',
            field=models.TextField(blank=True, help_text='English translation of the lesson text'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='grammar_points',
            field=models.TextField(blank=True, help_text='Key grammar points covered in the lesson'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='pinyin_text',
            field=models.TextField(blank=True, help_text='Pinyin for the lesson text'),
        ),
    ]
