# Generated by Django 5.2 on 2025-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandarin_vocab', '0004_bookchapter_chinese_text_bookchapter_cultural_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='cultural_notes',
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='grammar_points',
        ),
        migrations.RemoveField(
            model_name='bookchapter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='hskbook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hskbook',
            name='title',
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='cultural_notes_en',
            field=models.TextField(blank=True, help_text='Cultural context and notes (English)', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='cultural_notes_zh',
            field=models.TextField(blank=True, help_text='Cultural context and notes (Chinese)', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='description_zh',
            field=models.TextField(blank=True, help_text='Chinese description', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='grammar_points_en',
            field=models.TextField(blank=True, help_text='Key grammar points covered in the lesson (English)', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='grammar_points_zh',
            field=models.TextField(blank=True, help_text='Key grammar points covered in the lesson (Chinese)', null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='title_zh',
            field=models.CharField(blank=True, help_text='Chinese title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hskbook',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description', null=True),
        ),
        migrations.AddField(
            model_name='hskbook',
            name='description_zh',
            field=models.TextField(blank=True, help_text='Chinese description', null=True),
        ),
        migrations.AddField(
            model_name='hskbook',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hskbook',
            name='title_zh',
            field=models.CharField(blank=True, help_text='Chinese title', max_length=200, null=True),
        ),
    ]
