# Generated by Django 5.2 on 2025-05-01 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('pattern', models.TextField()),
                ('example', models.TextField()),
                ('hsk_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('category', models.CharField(choices=[('basic', 'Basic Grammar'), ('intermediate', 'Intermediate Grammar'), ('advanced', 'Advanced Grammar'), ('particles', 'Particles'), ('sentence', 'Sentence Patterns')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grammar Lesson',
                'verbose_name_plural': 'Grammar Lessons',
                'ordering': ['hsk_level', 'grammar_id'],
            },
        ),
    ]
