# Generated by Django 5.2 on 2025-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0004_timelinepost_comment_reaction_userconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarlesson',
            name='example',
        ),
        migrations.RemoveField(
            model_name='grammarlesson',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='grammarlesson',
            name='title',
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='example_en',
            field=models.TextField(blank=True, help_text='Example in English', null=True),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='example_zh',
            field=models.TextField(blank=True, help_text='Example in Chinese', null=True),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='pattern_en',
            field=models.TextField(blank=True, help_text='Grammar pattern in English', null=True),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='pattern_zh',
            field=models.TextField(blank=True, help_text='Grammar pattern in Chinese', null=True),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='title_zh',
            field=models.CharField(blank=True, help_text='Chinese title', max_length=200, null=True),
        ),
    ]
